// Generated by CoffeeScript 1.7.1
describe("CalcLogic.add 関数のテスト", function() {
  it("1 + 1 は 2", function() {
    return expect(CalcLogic.add(1, 1)).toBe(2);
  });
  it("1 + 3 は 4", function() {
    return expect(CalcLogic.add(1, 4)).toBe(5);
  });
  it("10 + 20 は 30", function() {
    return expect(CalcLogic.add(10, 20)).toBe(30);
  });
  it("1 + 1 は 2", function() {
    return expect(CalcLogic.add(1, 1)).toBe(2);
  });
  it("文字列を与えるとエラー（左）", function() {
    var e;
    try {
      return CalcLogic.add("Hello", 1);
    } catch (_error) {
      e = _error;
      return expect(e).toBe("numbers have to be integer.");
    }
  });
  it("文字列を与えるとエラー（右）", function() {
    var e;
    try {
      return CalcLogic.add(1, "Hello");
    } catch (_error) {
      e = _error;
      return expect(e).toBe("numbers have to be integer.");
    }
  });
});
