// Generated by CoffeeScript 1.7.1
$(function() {
  h5.api.geo.getCurrentPosition().then(function(data) {
    return $('#map1').gmap3({
      map: {
        latLng: [data.coords.latitude, data.coords.longitude],
        options: {
          zoom: 15
        }
      },
      marker: {
        latLng: [data.coords.latitude, data.coords.longitude]
      }
    });
  });
  return h5.api.geo.watchPosition().progress(function(data) {
    return $('#map2').gmap3({
      map: {
        latLng: [data.coords.latitude, data.coords.longitude],
        options: {
          zoom: 15
        }
      },
      marker: {
        latLng: [data.coords.latitude, data.coords.longitude]
      }
    });
  });
});
