// Generated by CoffeeScript 1.7.1
$(function() {
  test("a basic test example", function() {
    var value;
    ok(true, "this test is fine");
    value = "hello";
    return equal("hello", value, "We expect value to be hello");
  });
  test("getItemData", function() {
    var logic;
    logic = h5.core.logic(ItemSearchController.itemSearchLogic);
    return logic._getItemData(1).then(function(data) {
      return equal(data.length, 20, "We expect data length is 20.");
    });
  });
  return test("getItemList", function() {
    var logic;
    logic = h5.core.logic(ItemSearchController.itemSearchLogic);
    return logic.getItemList(1).then(function(data1) {
      equal(data1.length, 20, "We expect data length is 20.");
      return logic._getItemData(1).then(function(data2) {
        return equal(data1.length, data2.length, "We expect data1 length is equal to data2 length");
      });
    });
  });
});
