// Generated by CoffeeScript 1.7.1
$(function() {
  var Item, item;
  h5.core.data.createManager('DatabaseManager', 'db');
  Item = db.DatabaseManager.createModel({
    name: "Item",
    schema: {
      id: {
        id: true
      },
      name: {
        type: 'string'
      },
      point: {
        type: 'integer',
        defaultValue: 0
      },
      message: {
        type: 'string',
        depend: {
          on: ['name', 'point'],
          calc: function(e) {
            return "" + (this.get('name')) + "は" + (this.get('point')) + "です。";
          }
        }
      }
    }
  });
  item = Item.create({
    id: '1',
    name: "テストのアイテム",
    point: 100
  });
  Item.addEventListener('itemsChange', function(e) {
    console.log('データモデル', 'Change!');
    return console.log(e);
  });
  item.addEventListener('change', function(e) {
    return console.log('データアイテム', 'Change!');
  });
  console.info(item);
  console.info(item.get('name'));
  item.set('point', 50);
  return console.info(item.get('message'));
});
